resolver: lts-14.27
packages: 
  - .
extra-deps: 
 - diagrams-graphviz-1.4.1.1@sha256:e71afa8f89904c2a6a2cb490dba7108c6425779c2174b90bd90dbaf507a9d3dc,1388
build:
  library-profiling: true
  executable-profiling: true
